apiVersion: v1
kind: Service
metadata:
  name: keti-gpu-device-plugin
  namespace: gpu
  labels:
    name: keti-gpu-device-plugin
spec:
  type: LoadBalancer
  ports:
  - port: 2052
    targetPort: 2052
    nodePort: 32052
    protocol: TCP
  selector:
    name: keti-gpu-device-plugin