kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keti-gpu-device-plugin
  namespace: gpu
subjects:
- kind: ServiceAccount
  name: keti-gpu-device-plugin
  namespace: gpu
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io